#!/bin/sh
scp -q -o LogLevel=QUIET -r ~/tractor-scala/src 172.16.1.113:~/tractor-scala
ssh 172.16.1.113 '(killall -9 java; cd ~/tractor-scala/; sbt -mem 6000 "run-main ru.laboshinl.tractor.ApplicationMain";) &>/tmp/akka.log &'

scp -q -o LogLevel=QUIET -r ~/tractor-scala/src 172.16.1.114:~/tractor-scala
ssh 172.16.1.114 '(killall -9 java; cd ~/tractor-scala/; sbt -mem 6000 "run-main ru.laboshinl.tractor.ApplicationMain";) &>/tmp/akka.log &'
scp -q -o LogLevel=QUIET -r ~/tractor-scala/src 172.16.1.115:~/tractor-scala
ssh 172.16.1.115 '(killall -9 java; cd ~/tractor-scala/; sbt -mem 6000 "run-main ru.laboshinl.tractor.ApplicationMain";) &>/tmp/akka.log &'
scp -q -o LogLevel=QUIET -r ~/tractor-scala/src 172.16.1.116:~/tractor-scala
ssh 172.16.1.116 '(killall -9 java; cd ~/tractor-scala/; sbt -mem 6000 "run-main ru.laboshinl.tractor.ApplicationMain";) &>/tmp/akka.log &'
scp -q -o LogLevel=QUIET -r ~/tractor-scala/src 172.16.1.117:~/tractor-scala
ssh 172.16.1.117 '(killall -9 java; cd ~/tractor-scala/; sbt -mem 6000 "run-main ru.laboshinl.tractor.ApplicationMain";) &>/tmp/akka.log &'
scp -q -o LogLevel=QUIET -r ~/tractor-scala/src 172.16.1.118:~/tractor-scala
ssh 172.16.1.118 '(killall -9 java; cd ~/tractor-scala/; sbt -mem 6000 "run-main ru.laboshinl.tractor.ApplicationMain";) &>/tmp/akka.log &'
scp -q -o LogLevel=QUIET -r ~/tractor-scala/src 172.16.1.119:~/tractor-scala
ssh 172.16.1.119 '(killall -9 java; cd ~/tractor-scala/; sbt -mem 6000 "run-main ru.laboshinl.tractor.ApplicationMain";) &>/tmp/akka.log &'
scp -q -o LogLevel=QUIET -r ~/tractor-scala/src 172.16.1.120:~/tractor-scala
ssh 172.16.1.120 '(killall -9 java; cd ~/tractor-scala/; sbt -mem 6000 "run-main ru.laboshinl.tractor.ApplicationMain";) &>/tmp/akka.log &'
scp -q -o LogLevel=QUIET -r ~/tractor-scala/src 172.16.1.121:~/tractor-scala
ssh 172.16.1.121 '(killall -9 java; cd ~/tractor-scala/; sbt -mem 6000 "run-main ru.laboshinl.tractor.ApplicationMain";) &>/tmp/akka.log &'

killall -9 java; cd ~/tractor-scala/; sbt -mem 6000 "run-main ru.laboshinl.tractor.ApplicationMain /home/ubuntu/pcaps/bigFlows.pcap"



